### ISSUE TITLE
open a thread to convert

### ISSUE THREAD

**Issue by windrunner414** [zonble/flutter_open_chinese_convert#1]
flutter does not support use MethodChannel in isolate, can the plugin open a thread to do convert and return the result?
do these in a thread: converter.convert,  result.success

**Comment by zonble** [comment]
I added a new parameter `inBackground` in the method `ChineseConverter.convert`. Once the parameter is set to true, the library uses GCD on iOS and coroutines on Android while doing text conversion.

Please give the version 0.2.0 a try.
