### ISSUE TITLE
0.3.3 run error

### ISSUE THREAD

**Issue by XIONG-WEN** [zonble/flutter_open_chinese_convert#13]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform lib-opencc-android-0.8.0.aar (com.zqc.opencc.android.lib:lib-opencc-android:0.8.0) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
      > Could not find lib-opencc-android-0.8.0.aar (com.zqc.opencc.android.lib:lib-opencc-android:0.8.0).
        Searched in the following locations:
            https://jcenter.bintray.com/com/zqc/opencc/android/lib/lib-opencc-android/0.8.0/lib-opencc-android-0.8.0.aar

**Comment by Predidit** [comment]
It has been fixed by #12 on master branch.

But it haven't been published to pub.dev. 

@XIONG-WEN Maybe we can make a new release now?
