### ISSUE TITLE
Ios simulator

### ISSUE THREAD

**Issue by mathgameapi** [zonble/flutter_open_chinese_convert#2]
When i run the code in vscode. app will crash.

I open with xcode. I got following error.

dyld: Library not loaded: @rpath/OpenCCBridge.framework/OpenCCBridge
  Referenced from: /Users/ken/Library/Developer/CoreSimulator/Devices/BCD237D5-ABBE-4F6E-9C79-506BA06E3B53/data/Containers/Bundle/Application/AF95F373-24A8-4345-A76B-82F98B0D2558/Runner.app/Runner
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/ken/Library/Developer/CoreSimulator/Caches/dyld/19G2021/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A372
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/ken/Desktop/development/flutter_code/opencc/build/ios/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Conte
(lldb)

**Comment by revabu** [comment]
I ran into the same error on ios simulator as well.

My app worked fine with the flutter_open_chinese_convert package several months ago. When I tried running the exact same app today, I ran into this issue.

Some people with similar error was able to fix it by tweaking stuff in xcode or reinstalling cocaopods, etc. Unfortunately none of their workarounds worked for me so far.

**Comment by zonble** [comment]
It seems that Xcode 12 does not automatically embed the frameworks that we use "vendored_frameworks" that we ask Xcode 12 to embed. To fix the issue, open your Xcode workspace, and drag `OpenCCBridge.framework`
to your app target, the like following image.

![xcode12](https://user-images.githubusercontent.com/53011/97072607-0b9d9b00-1613-11eb-8194-954b1fe280c1.png)
