### ISSUE TITLE
ios xcode error

### ISSUE THREAD

**Issue by sammrafi** [zonble/flutter_open_chinese_convert#5]
Hi, I'm using this library in my flutter app. as you provide in pub.dev. After adding manually OpenCCBridge.framework it can't run perfetly. I fix that problem but when I run validate app in xcode for app store  then it's showing invalid identifier please help

**Comment by sammrafi** [comment]
here is the error

ERROR ITMS-90334: "Invalid Code Signature Identifier. The identifier "OpenCCBridge-55554944e65952b5839731b28b5926dbd95a0b1b" in your code signature for "OpenCCBridge" must match its Bundle Identifier "OpenCCBridge""

**Comment by zonble** [comment]
Fixed.
